[package]
name = "snake"
version = "1.0.0"
authors = ["Mayank Tripathi <ryotsu@kochika.me>"]
edition = "2018"

[lib]
name = "snake"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.35.0"
lzw = "0.10.0"
rand = "0.8.5"
