[package]
name = "snake_gif"
version = "0.1.0"
authors = []

[lib]
name = "snake_gif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.15.1"
rustler_codegen = "0.15.1"
lazy_static = "0.2"
rand = "0.3.18"
lzw = "0.10.0"
